-- Complete Film Categories Data for Festival Ready v2.0
-- All 80+ film categories from Film Festival Circuit

INSERT INTO film_categories (category_name, format_type, min_runtime, max_runtime, audience_type, description, award_name) VALUES
-- Action Categories
('Action Feature Film', 'feature_film', 31, 120, 'general', 'Submit your action feature film, 31-120 minutes in length including credits. Enter your action film in this dynamic category if it features high-octane sequences such as fights, chases, driving scenes, acrobatics, gun battles, or martial arts.', 'Best Action Feature Film Award'),
('Action Film', 'film', 7, 30, 'general', 'Submit your action film, 7-30 minutes in length including credits. Enter your action film in this dynamic category if it features high-octane sequences such as fights, chases, driving scenes, acrobatics, gun battles, or martial arts.', 'Best Action Film Award'),
('Action Micro Film', 'micro_film', 1, 6, 'general', 'Submit your action micro film, 6 minutes or less including credits. Enter your action film in this dynamic category if it features high-octane sequences such as fights, chases, driving scenes, acrobatics, gun battles, or martial arts.', 'Best Action Micro Film Award'),

-- Animated Categories
('Animated Comedy Film', 'film', 7, 30, 'general', 'Submit your animated comedy film, 7-30 minutes in length including credits. Our judges are looking for creative animation that blends humor, expressive character animation, and laugh-out-loud moments into a cohesive story where the comedy flows naturally throughout.', 'Best Animated Comedy Film Award'),
('Animated Film', 'film', 7, 30, 'general', 'Submit your animated film, 7-30 minutes in length including credits. Our judges are looking for creative animation that showcases artistic vision, technical excellence, and compelling storytelling through the animated medium.', 'Best Animated Film Award'),

-- Comedy Categories
('Comedy Feature Film', 'feature_film', 31, 120, 'general', 'Submit your comedy feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor flows naturally throughout.', 'Best Comedy Feature Film Award'),
('Comedy Film', 'film', 7, 30, 'general', 'Submit your comedy film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor flows naturally throughout.', 'Best Comedy Film Award'),
('Comedy Micro Film', 'micro_film', 1, 6, 'general', 'Submit your comedy micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor flows naturally throughout.', 'Best Comedy Micro Film Award'),
('Comedy Series Episode', 'series_episode', 1, 30, 'general', 'Submit your comedy series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances, and laugh-out-loud scenes into a cohesive episode where the humor flows naturally throughout.', 'Best Comedy Series Episode Award'),

-- Dark Comedy Categories
('Dark Comedy Feature Film', 'feature_film', 31, 120, 'mature', 'Submit your dark comedy feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor, often sharp and unexpected, flows naturally throughout.', 'Best Dark Comedy Feature Film Award'),
('Dark Comedy Film', 'film', 7, 30, 'mature', 'Submit your dark comedy film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor, often sharp and unexpected, flows naturally throughout.', 'Best Dark Comedy Film Award'),
('Dark Comedy Micro Film', 'micro_film', 1, 6, 'mature', 'Submit your dark comedy micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor, often sharp and unexpected, flows naturally throughout.', 'Best Dark Comedy Micro Film Award'),
('Dark Comedy Series Episode', 'series_episode', 1, 30, 'mature', 'Submit your dark comedy series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that blends sharp dialogue, edgy performances, and laugh-out-loud scenes into a cohesive episode where the dark humor flows naturally throughout.', 'Best Dark Comedy Series Episode Award'),

-- Dark Drama Categories
('Dark Drama Feature Film', 'feature_film', 31, 120, 'mature', 'Submit your dark drama feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that explores mature themes with intensity and depth, blending powerful dialogue, raw performances with clear character arcs, and emotionally challenging scenes into a cohesive story.', 'Best Dark Drama Feature Film Award'),
('Dark Drama Film', 'film', 7, 30, 'mature', 'Submit your dark drama film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that explores mature themes with intensity and depth, blending powerful dialogue, raw performances with clear character arcs, and emotionally challenging scenes into a cohesive story.', 'Best Dark Drama Film Award'),
('Dark Drama Micro Film', 'micro_film', 1, 6, 'mature', 'Submit your dark drama micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that explores mature themes with intensity and depth, blending powerful dialogue, raw performances with clear character arcs, and emotionally challenging scenes into a cohesive story.', 'Best Dark Drama Micro Film Award'),
('Dark Drama Series Episode', 'series_episode', 1, 30, 'mature', 'Submit your dark drama series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that explores mature themes with intensity and depth, blending powerful dialogue, raw performances, and emotionally challenging scenes into a cohesive episode.', 'Best Dark Drama Series Episode Award'),

-- Dark Fantasy Categories
('Dark Fantasy Feature Film', 'feature_film', 31, 120, 'mature', 'Submit your dark fantasy feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that blends otherworldly elements with mature themes, featuring magic, supernatural beings, or mythical creatures in darker, more intense settings.', 'Best Dark Fantasy Feature Film Award'),
('Dark Fantasy Film', 'film', 7, 30, 'mature', 'Submit your dark fantasy film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that blends otherworldly elements with mature themes, featuring magic, supernatural beings, or mythical creatures in darker, more intense settings.', 'Best Dark Fantasy Film Award'),
('Dark Fantasy Micro Film', 'micro_film', 1, 6, 'mature', 'Submit your dark fantasy micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that blends otherworldly elements with mature themes, featuring magic, supernatural beings, or mythical creatures in darker, more intense settings.', 'Best Dark Fantasy Micro Film Award'),
('Dark Fantasy Series Episode', 'series_episode', 1, 30, 'mature', 'Submit your dark fantasy series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that blends otherworldly elements with mature themes, featuring magic, supernatural beings, or mythical creatures in darker, more intense settings.', 'Best Dark Fantasy Series Episode Award'),

-- Dark Science Fiction Categories
('Dark Science Fiction Feature Film', 'feature_film', 31, 120, 'mature', 'Submit your dark science fiction feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that explores dystopian futures, alien invasions, technological nightmares, or scientific experiments gone wrong with mature themes and intensity.', 'Best Dark Science Fiction Feature Film Award'),
('Dark Science Fiction Film', 'film', 7, 30, 'mature', 'Submit your dark science fiction film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that explores dystopian futures, alien invasions, technological nightmares, or scientific experiments gone wrong with mature themes and intensity.', 'Best Dark Science Fiction Film Award'),
('Dark Science Fiction Micro Film', 'micro_film', 1, 6, 'mature', 'Submit your dark science fiction micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that explores dystopian futures, alien invasions, technological nightmares, or scientific experiments gone wrong with mature themes and intensity.', 'Best Dark Science Fiction Micro Film Award'),
('Dark Science Fiction Series Episode', 'series_episode', 1, 30, 'mature', 'Submit your dark science fiction series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that explores dystopian futures, alien invasions, technological nightmares, or scientific experiments gone wrong with mature themes and intensity.', 'Best Dark Science Fiction Series Episode Award'),

-- Documentary Categories
('Documentary Feature Film', 'feature_film', 31, 120, 'general', 'Submit your documentary feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that blends insightful interviews, compelling real-world footage, and truthful storytelling into a cohesive documentary where the narrative and information flow naturally throughout.', 'Best Documentary Feature Film Award'),
('Documentary Film', 'film', 7, 30, 'general', 'Submit your documentary film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that blends insightful interviews, compelling real-world footage, and truthful storytelling into a cohesive documentary where the narrative and information flow naturally throughout.', 'Best Documentary Film Award'),
('Documentary Micro Film', 'micro_film', 1, 6, 'general', 'Submit your documentary micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that blends insightful interviews, compelling real-world footage, and truthful storytelling into a cohesive documentary where the narrative and information flow naturally throughout.', 'Best Documentary Micro Film Award'),
('Documentary Music Video', 'music_video', 1, 10, 'general', 'Submit your documentary music video, 10 minutes or less including credits. Our judges are looking for music videos that blend documentary storytelling with musical performance or soundtrack. These videos tell real stories, feature actual events or people, and use documentary techniques while being driven by music.', 'Best Documentary Music Video Award'),
('Documentary Series Episode', 'series_episode', 1, 30, 'general', 'Submit your documentary series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that blends insightful interviews, compelling real-world footage, and truthful storytelling into a cohesive documentary episode.', 'Best Documentary Series Episode Award'),

-- Drama Categories
('Drama Feature Film', 'feature_film', 31, 120, 'general', 'Submit your drama feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that blends compelling dialogue, powerful performances with clear character arcs, and emotionally resonant scenes into a cohesive story where the dramatic tension flows naturally throughout.', 'Best Drama Feature Film Award'),
('Drama Film', 'film', 7, 30, 'general', 'Submit your drama film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that blends compelling dialogue, powerful performances with clear character arcs, and emotionally resonant scenes into a cohesive story where the dramatic tension flows naturally throughout.', 'Best Drama Film Award'),
('Drama Micro Film', 'micro_film', 1, 6, 'general', 'Submit your drama micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that blends compelling dialogue, powerful performances with clear character arcs, and emotionally resonant scenes into a cohesive story where the dramatic tension flows naturally throughout.', 'Best Drama Micro Film Award'),
('Drama Series Episode', 'series_episode', 1, 30, 'general', 'Submit your drama series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that blends compelling dialogue, powerful performances, and emotionally resonant scenes into a cohesive episode where the dramatic tension flows naturally throughout.', 'Best Drama Series Episode Award'),

-- Experimental Categories
('Experimental Feature Film', 'feature_film', 31, 120, 'general', 'Submit your experimental feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that pushes boundaries through innovative techniques, unconventional narratives, and artistic expression that challenges traditional filmmaking.', 'Best Experimental Feature Film Award'),
('Experimental Film', 'film', 7, 30, 'general', 'Submit your experimental film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that pushes boundaries through innovative techniques, unconventional narratives, and artistic expression that challenges traditional filmmaking.', 'Best Experimental Film Award'),
('Experimental Micro Film', 'micro_film', 1, 6, 'general', 'Submit your experimental micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that pushes boundaries through innovative techniques, unconventional narratives, and artistic expression that challenges traditional filmmaking.', 'Best Experimental Micro Film Award'),
('Experimental Music Video', 'music_video', 1, 6, 'general', 'Submit your experimental music video, 6 minutes or less including credits. Our judges are looking for music videos that push creative boundaries through innovative visual techniques, unconventional narratives, and artistic expression.', 'Best Experimental Music Video Award'),

-- Fantasy Categories
('Fantasy Feature Film', 'feature_film', 31, 120, 'general', 'Submit your fantasy feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that blends magical dialogue, enchanting performances with clear character arcs, and wondrous scenes into a cohesive story where the fantasy elements flow naturally throughout.', 'Best Fantasy Feature Film Award'),
('Fantasy Film', 'film', 7, 30, 'general', 'Submit your fantasy film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that blends magical dialogue, enchanting performances with clear character arcs, and wondrous scenes into a cohesive story where the fantasy elements flow naturally throughout.', 'Best Fantasy Film Award'),
('Fantasy Micro Film', 'micro_film', 1, 6, 'general', 'Submit your fantasy micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that blends magical dialogue, enchanting performances with clear character arcs, and wondrous scenes into a cohesive story where the fantasy elements flow naturally throughout.', 'Best Fantasy Micro Film Award'),
('Fantasy Series Episode', 'series_episode', 1, 30, 'general', 'Submit your fantasy series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that blends magical dialogue, enchanting performances, and wondrous scenes into a cohesive episode where the fantasy elements flow naturally throughout.', 'Best Fantasy Series Episode Award'),

-- Horror Categories
('Horror Feature Film', 'feature_film', 31, 120, 'mature', 'Submit your horror feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that blends frightening dialogue, chilling performances with clear character arcs, and terrifying scenes into a cohesive story where the horror and dread flow naturally throughout.', 'Best Horror Feature Film Award'),
('Horror Film', 'film', 7, 30, 'mature', 'Submit your horror film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that blends frightening dialogue, chilling performances with clear character arcs, and terrifying scenes into a cohesive story where the horror and dread flow naturally throughout.', 'Best Horror Film Award'),
('Horror Micro Film', 'micro_film', 1, 6, 'mature', 'Submit your horror micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that blends frightening dialogue, chilling performances with clear character arcs, and terrifying scenes into a cohesive story where the horror and dread flow naturally throughout.', 'Best Horror Micro Film Award'),
('Horror Music Video', 'music_video', 1, 6, 'mature', 'Submit your horror music video, 6 minutes or less including credits. Our judges are looking for music videos that embrace horror aesthetics, featuring frightening imagery, dark atmospheres, and terrifying visuals that sync with the music.', 'Best Horror Music Video Award'),
('Horror Series Episode', 'series_episode', 1, 30, 'mature', 'Submit your horror series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that blends frightening dialogue, chilling performances, and terrifying scenes into a cohesive episode where the horror and dread flow naturally throughout.', 'Best Horror Series Episode Award'),

-- Horror Comedy Categories
('Horror Comedy Feature Film', 'feature_film', 31, 120, 'general', 'Submit your horror comedy feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor flows naturally throughout. Horror comedies poke fun at or parody the horror genre.', 'Best Horror Comedy Feature Film Award'),
('Horror Comedy Film', 'film', 7, 30, 'general', 'Submit your horror comedy film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor flows naturally throughout. Horror comedies poke fun at or parody the horror genre.', 'Best Horror Comedy Film Award'),
('Horror Comedy Micro Film', 'micro_film', 1, 6, 'general', 'Submit your horror comedy micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor flows naturally throughout. Horror comedies poke fun at or parody the horror genre.', 'Best Horror Comedy Micro Film Award'),
('Horror Comedy Series Episode', 'series_episode', 1, 30, 'general', 'Submit your horror comedy series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances, and laugh-out-loud scenes into a cohesive episode where the humor flows naturally throughout. Horror comedies poke fun at or parody the horror genre.', 'Best Horror Comedy Series Episode Award'),

-- Mockumentary Categories
('Mockumentary Feature Film', 'feature_film', 31, 120, 'general', 'Submit your mockumentary feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that uses a comedic documentary-style approach to blur the line between fiction and reality.', 'Best Mockumentary Feature Film Award'),
('Mockumentary Film', 'film', 7, 30, 'general', 'Submit your mockumentary film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that uses a comedic documentary-style approach to blur the line between fiction and reality.', 'Best Mockumentary Film Award'),
('Mockumentary Micro Film', 'micro_film', 1, 6, 'general', 'Submit your mockumentary micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that uses a comedic documentary-style approach to blur the line between fiction and reality.', 'Best Mockumentary Micro Film Award'),
('Mockumentary Series Episode', 'series_episode', 1, 30, 'general', 'Submit your mockumentary series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that uses a comedic documentary-style approach to blur the line between fiction and reality.', 'Best Mockumentary Series Episode Award'),

-- Music Video Categories
('Music Video', 'music_video', 1, 6, 'general', 'Submit your music video, 6 minutes or less including credits. Our judges are looking for music videos of all musical genres. They are impressed by good stories, great acting, excellent cinematography, and cool editing that syncs really well with the music.', 'Best Music Video Award'),
('Funny Music Video', 'music_video', 1, 6, 'general', 'Submit your funny music video, 6 minutes or less including credits. Our judges are looking for music videos that prioritize humor and comedy, whether through parody, satire, slapstick, or clever visual gags.', 'Best Funny Music Video Award'),

-- Relationship Drama Categories
('Relationship Drama Feature Film', 'feature_film', 31, 120, 'general', 'Submit your relationship drama feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that explores situations and characters that feel real, authentic, and relatable, blending real dialogue, relatable characters with clear arcs, and touching drama into a deep story that resonates throughout.', 'Best Relationship Drama Feature Film Award'),
('Relationship Drama Film', 'film', 7, 30, 'general', 'Submit your relationship drama film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that explores situations and characters that feel real, authentic, and relatable, blending real dialogue, relatable characters with clear arcs, and touching drama into a deep story that resonates throughout.', 'Best Relationship Drama Film Award'),
('Relationship Drama Micro Film', 'micro_film', 1, 6, 'general', 'Submit your relationship drama micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that explores situations and characters that feel real, authentic, and relatable, blending real dialogue, relatable characters with clear arcs, and touching drama into a deep story that resonates throughout.', 'Best Relationship Drama Micro Film Award'),
('Relationship Drama Series Episode', 'series_episode', 1, 30, 'general', 'Submit your relationship drama series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that explores situations and characters that feel real, authentic, and relatable, blending real dialogue, relatable characters with clear arcs, and touching drama into a deep story that resonates throughout.', 'Best Relationship Drama Series Episode Award'),

-- Romantic Comedy Categories
('Romantic Comedy Feature Film', 'feature_film', 31, 120, 'general', 'Submit your romantic comedy feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor flows naturally throughout.', 'Best Romantic Comedy Feature Film Award'),
('Romantic Comedy Film', 'film', 7, 30, 'general', 'Submit your romantic comedy film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor flows naturally throughout.', 'Best Romantic Comedy Film Award'),
('Romantic Comedy Micro Film', 'micro_film', 1, 6, 'general', 'Submit your romantic comedy micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances with clear character arcs, and laugh-out-loud scenes into a cohesive story where the humor flows naturally throughout.', 'Best Romantic Comedy Micro Film Award'),
('Romantic Comedy Series Episode', 'series_episode', 1, 30, 'general', 'Submit your romantic comedy series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that blends fun dialogue, lively performances, and laugh-out-loud scenes into a cohesive episode where the humor flows naturally throughout.', 'Best Romantic Comedy Series Episode Award'),

-- Science Fiction Categories
('Science Fiction Feature Film', 'feature_film', 31, 120, 'general', 'Submit your science fiction feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that weaves imaginative stories featuring themes like futuristic technology, medical advancements, time travel, space exploration, aliens, mythological or genetically engineered creatures.', 'Best Science Fiction Feature Film Award'),
('Science Fiction Film', 'film', 7, 30, 'general', 'Submit your science fiction film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that weaves imaginative stories featuring themes like futuristic technology, medical advancements, time travel, space exploration, aliens, mythological or genetically engineered creatures.', 'Best Science Fiction Film Award'),
('Science Fiction Micro Film', 'micro_film', 1, 6, 'general', 'Submit your science fiction micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that weaves imaginative stories featuring themes like futuristic technology, medical advancements, time travel, space exploration, aliens, mythological or genetically engineered creatures.', 'Best Science Fiction Micro Film Award'),
('Science Fiction Series Episode', 'series_episode', 1, 30, 'general', 'Submit your science fiction series episode, a maximum of 30 minutes including credits. Our judges are looking for creative filmmaking that weaves imaginative stories featuring themes like futuristic technology, medical advancements, time travel, space exploration, aliens, mythological or genetically engineered creatures.', 'Best Science Fiction Series Episode Award'),

-- Suspense Thriller Categories
('Suspense Thriller Feature Film', 'feature_film', 31, 120, 'general', 'Submit your suspense thriller feature film, 31-120 minutes in length including credits. Our judges are looking for creative filmmaking that blends tense dialogue, gripping performances with clear character arcs, and nerve-wracking scenes into a cohesive story where the suspense and tension flow naturally throughout.', 'Best Suspense Thriller Feature Film Award'),
('Suspense Thriller Film', 'film', 7, 30, 'general', 'Submit your suspense thriller film, 7-30 minutes in length including credits. Our judges are looking for creative filmmaking that blends tense dialogue, gripping performances with clear character arcs, and nerve-wracking scenes into a cohesive story where the suspense and tension flow naturally throughout.', 'Best Suspense Thriller Film Award'),
('Suspense Thriller Micro Film', 'micro_film', 1, 6, 'general', 'Submit your suspense thriller micro film, 6 minutes or less including credits. Our judges are looking for creative filmmaking that blends tense dialogue, gripping performances with clear character arcs, and nerve-wracking scenes into a cohesive story where the suspense and tension flow naturally throughout.', 'Best Suspense Thriller Micro Film Award');
